import { task, int, nz, pick, distinct, V, C, M, R, lin, frac, vec, dot, add, scale, randomMatrix, diag, mul, mv, transpose, det, power, plus, times, blockDiag, number, vector, matrix, choice, yesno, computedMatrix, computedVector, type Matrix, type WorkshopTasks } from "./core.ts";

const quarter = (k: number): Matrix => ([[[1, 0], [0, 1]], [[0, -1], [1, 0]], [[-1, 0], [0, -1]], [[0, 1], [-1, 0]]] as Matrix[])[((k % 4) + 4) % 4];
const angle = (k: number) => ["0", "⟬π¦2⟭", "π", "⟬3π¦2⟭"][((k % 4) + 4) % 4];

export const euclidean: WorkshopTasks = {
  "inner-product-tuner": [
    task("scalar-product", "Calculer un produit scalaire", () => { const u = vec(3), v = vec(3); return number("Calculer ⟨u,v⟩.", `ℝ³ est muni du produit scalaire usuel ; u = ${V(u)}, v = ${V(v)}.`, dot(u, v), "On additionne les produits des coordonnées de même indice.", { kind: "dot", inputs: [u, v], expected: dot(u, v) }); }),
    task("norm", "Calculer une norme", () => { const k = int(1, 4), u = [3 * k, 4 * k]; return number("Quelle est la norme de u ?", `Dans le plan euclidien usuel, u = ${V(u)}.`, 5 * k, "La norme est la racine carrée de la somme des carrés des coordonnées."); }),
    task("distance", "Calculer une distance au carré", () => { const u = vec(3), v = vec(3), d = add(u, scale(-1, v)); return number("Calculer d(u,v)².", `Dans ℝ³ euclidien usuel, u = ${V(u)}, v = ${V(v)}.`, dot(d, d), "La distance au carré est ‖u−v‖².", { kind: "distance-squared", inputs: [u, v], expected: dot(d, d) }); }),
    task("angle", "Calculer le cosinus d’un angle", () => { const a = pick([3, -3]), b = pick([4, -4]); return choice("Quel est le cosinus de l’angle entre u et v ?", `u = (1 ; 0), v = ${V([a, b])}, produit scalaire usuel.`, frac(a, 5), [frac(-a, 5), frac(b, 5), "0"], "Le cosinus est ⟨u,v⟩/(‖u‖‖v‖) = a/5."); }),
    task("cauchy-equality", "Reconnaître l’égalité dans Cauchy–Schwarz", () => { const a = nz(), k = nz(), u = [1, a]; return choice("Pour quel vecteur v a-t-on |⟨u,v⟩| = ‖u‖‖v‖ ?", `u = ${V(u)} dans le plan euclidien usuel.`, V(scale(k, u)), [1, 2, 3].map(d => V([k, a * k + d])), "L’égalité dans Cauchy–Schwarz caractérise les vecteurs colinéaires."); }),
  ],
  "schmidt-orthogonalizer": [
    task("orthogonalize", "Retirer une composante parallèle", () => { const a = nz(), b = nz(); return vector("Quel vecteur w = v − ⟨v,u⟩u est orthogonal à u ?", `u = (1 ; 0), v = ${V([a, b])}, produit scalaire usuel.`, [0, b], "u est unitaire ; on retranche la première coordonnée de v."); }),
    task("normalize", "Normaliser un vecteur non nul", () => { const s = pick([-1, 1]), t = pick([-1, 1]); return choice("Quel est le vecteur u/‖u‖ ?", `u = ${V([3 * s, 4 * t])}`, V([frac(3 * s, 5), frac(4 * t, 5)]), [V([frac(-3 * s, 5), frac(4 * t, 5)]), V([3 * s, 4 * t]), V([frac(3 * s, 25), frac(4 * t, 25)])], "La norme de u vaut 5 ; on divise chaque coordonnée par 5."); }),
    task("schmidt-step", "Calculer le deuxième vecteur de Gram–Schmidt", () => { const a = nz(), b = nz(); return choice("Quel deuxième vecteur unitaire donne Gram–Schmidt dans cet ordre ?", `u = (1 ; 0), v = ${V([a, b])}`, V([0, Math.sign(b)]), [V([0, -Math.sign(b)]), V([1, 0]), V([-1, 0])], "Après retrait de la projection sur u, il reste (0;b), que l’on divise par |b|. Le signe est imposé par l’algorithme."); }),
    task("complete-oriented", "Compléter une base orthonormée directe", () => { const a = pick([3, -3]), b = pick([4, -4]); return choice("Quel vecteur v complète u en une base orthonormée directe ?", `u = ${V([frac(a, 5), frac(b, 5)])}, orientation canonique.`, V([frac(-b, 5), frac(a, 5)]), [V([frac(b, 5), frac(-a, 5)]), V([frac(a, 5), frac(b, 5)]), V([-b, a])], "Une rotation d’un quart de tour direct transforme (a/5;b/5) en (−b/5;a/5)."); }),
    task("projection-coefficient", "Calculer le coefficient d’orthogonalisation", () => { const a = nz(), b = nz(), c = nz(); return choice("Quel scalaire t rend v − tu orthogonal à u ?", `u = (1 ; ${a}), v = ${V([b, c])}`, frac(b + a * c, 1 + a * a), [frac(b + a * c + 1, 1 + a * a), frac(b + a * c - 1, 1 + a * a), frac(b + a * c + 2, 1 + a * a)], "La condition ⟨v−tu,u⟩=0 donne t=⟨v,u⟩/⟨u,u⟩."); }),
  ],
  "orthogonal-chamber": [
    task("orthogonal-line", "Déterminer l’orthogonal d’une droite", () => { const a = nz(); return choice("Quel est F^{⊥} ?", `F = Vect((1 ; ${a})) dans ℝ² euclidien usuel.`, `Vect((${ -a} ; 1))`, ["Vect((1 ; 0))", "ℝ²", "{0}"], "Les vecteurs orthogonaux satisfont x+ay=0."); }),
    task("dimension", "Calculer la dimension d’un orthogonal", () => { const n = int(3, 8), r = int(1, n - 1); return number("Quelle est dim(F^{⊥}) ?", `E est euclidien de dimension ${n}, dim(F) = ${r}.`, n - r, "E = F ⊕ F^{⊥}, donc les dimensions s’additionnent."); }),
    task("complete-coordinate", "Imposer l’orthogonalité par un paramètre", () => { const a = nz(), b = nz(), c = nz(); return number("Quelle valeur de t rend u et v orthogonaux ?", `u = (1 ; ${a} ; 1), v = (${b} ; ${c} ; t)`, -b - a * c, "Le produit scalaire b+ac+t doit s’annuler."); }),
    task("double-orthogonal", "Calculer un double orthogonal", () => { const a = nz(), n = int(3, 6); return number("Quelle est dim((F^{⊥})^{⊥}) ?", `F = Vect((1 ; ${a} ; 0 ; … ; 0)) dans ${R(n)} euclidien.`, 1, "En dimension finie, le double orthogonal est F lui-même ; ici F est une droite."); }),
    task("orthogonal-intersection", "Utiliser l’orthogonal d’une somme", () => { const n = int(4, 7), f = int(1, 2), g = int(1, 2); return number("Quelle est dim(F^{⊥} ∩ G^{⊥}) ?", `E est euclidien de dimension ${n}, F ⊥ G, dim(F) = ${f}, dim(G) = ${g}.`, n - f - g, "F^{⊥} ∩ G^{⊥} = (F+G)^{⊥} ; l’orthogonalité rend la somme directe."); }),
  ],
  "metric-projector": [
    task("coordinate-plane", "Projeter sur un plan de coordonnées", () => { const u = vec(3); return vector("Quelle est la projection orthogonale de u sur F ?", `F = {(x ; y ; z) | z = 0}, u = ${V(u)}. Produit scalaire usuel.`, [u[0], u[1], 0], "On conserve les deux coordonnées dans le plan et on annule la composante normale."); }),
    task("oblique-line", "Projeter sur une droite non canonique", () => { const a = nz(), u = vec(), numerator = u[0] + a * u[1], denominator = 1 + a * a; return choice("Quelle est la projection orthogonale de u sur F ?", `F = Vect((1 ; ${a})), u = ${V(u)}. Produit scalaire usuel.`, V([frac(numerator, denominator), frac(a * numerator, denominator)]), [V([frac(numerator + 1, denominator), frac(a * numerator, denominator)]), V([frac(numerator, denominator), frac(a * numerator + 1, denominator)]), V([frac(numerator - 1, denominator), frac(a * numerator - 1, denominator)])], "p_F(u)=⟨u,v⟩v/‖v‖² avec v=(1;a)."); }),
    task("distance-line", "Calculer une distance à une droite", () => { const a = nz(), b = nz(); return choice("Quelle est la distance de u à F ?", `F = Vect((1 ; 1)), u = ${V([a, b])}. Produit scalaire usuel.`, frac(Math.abs(a - b), 1) === "0" ? "0" : `⟬${Math.abs(a - b)}¦√2⟭`, [`⟬${Math.abs(a - b) + 1}¦√2⟭`, `⟬${Math.abs(a - b) + 2}¦√2⟭`, `⟬${Math.abs(a - b) + 3}¦√2⟭`], "La composante normale sur (1;−1)/√2 a pour valeur absolue |a−b|/√2."); }),
    task("projection-matrix", "Construire une matrice de projection orthogonale", () => { const a = nz(), d = 1 + a * a; return choice("Quelle est la matrice de p_F dans la base canonique ?", `F = Vect((1 ; ${a})) dans le plan euclidien usuel.`, M([[frac(1, d), frac(a, d)], [frac(a, d), frac(a * a, d)]]), [M([[1, a], [0, 0]]), M([[1, 0], [0, 0]]), M([[0, 0], [0, 1]])], "La matrice est vvᵀ/(vᵀv) pour v=(1;a), ce qui donne une matrice symétrique et idempotente."); }),
    task("least-squares", "Minimiser une distance à une droite", () => { const a = nz(), b = nz(), c = nz(); return choice("Pour quelle valeur de t la distance ‖u − tv‖ est-elle minimale ?", `u = ${V([b, c])}, v = (1 ; ${a}), produit scalaire usuel.`, frac(b + a * c, 1 + a * a), [frac(b + a * c + 1, 1 + a * a), frac(b + a * c - 1, 1 + a * a), frac(b + a * c + 2, 1 + a * a)], "Le minimiseur est le coefficient de la projection : t=⟨u,v⟩/‖v‖²."); }),
  ],
  "orthogonal-matrix-gate": [
    task("orthogonality", "Vérifier une matrice orthogonale", () => { const a = pick([-1, 1, 2]), b = pick([-1, 1]); return yesno("A est-elle orthogonale ?", `A = ${M([[0, a], [b, 0]])}`, Math.abs(a) === 1, "Les colonnes sont orthogonales ; il faut aussi qu’elles soient toutes de norme 1."); }),
    task("inverse", "Inverser une matrice orthogonale", () => { const a = quarter(pick([1, 3])); return computedMatrix("Calculer Q⁻¹.", `Q = ${M(a)}`, "inverse", [a], transpose(a), "Pour une matrice orthogonale, l’inverse est la transposée."); }),
    task("determinant", "Calculer le déterminant d’une matrice orthogonale", () => { const a = blockDiag(quarter(int(0, 3)), [[pick([-1, 1])]]); return number("Quel est det(Q) ?", `Q = ${M(a)}`, det(a), "Le bloc de rotation a déterminant 1 ; le dernier coefficient diagonal donne le signe.", { kind: "det", inputs: [a], expected: det(a) }); }),
    task("complete-column", "Compléter une matrice orthogonale directe", () => { const a = pick([3, -3]), b = pick([4, -4]); return choice("Quelle seconde colonne rend Q orthogonale de déterminant 1 ?", `La première colonne de Q est ${C([frac(a, 5), frac(b, 5)])}.`, C([frac(-b, 5), frac(a, 5)]), [C([frac(b, 5), frac(-a, 5)]), C([frac(a, 5), frac(b, 5)]), C([-b, a])], "La seconde colonne est obtenue par un quart de tour direct de la première."); }),
    task("preserve-norm", "Utiliser la conservation de la norme", () => { const n = int(2, 8); return number("Quelle est la norme de Qx ?", `Q est orthogonale et ‖x‖ = ${n}.`, n, "QᵀQ=I implique ‖Qx‖²=xᵀQᵀQx=‖x‖²."); }),
  ],
  "isometry-forge": [
    task("test-isometry", "Reconnaître une isométrie linéaire", () => { const a = pick([-1, 1, 2]), b = pick([-1, 1]); return yesno("u est-il une isométrie du plan euclidien ?", `u(x,y) = (${lin([a], ["y"])} ; ${lin([b], ["x"])})`, Math.abs(a) === 1, "Il faut conserver la norme de tout vecteur ; les images des vecteurs canoniques doivent être orthonormées."); }),
    task("distance", "Transporter une distance", () => { const d = int(1, 9); return number("Quelle est la distance entre u(x) et u(y) ?", `u est une isométrie linéaire et d(x,y) = ${d}.`, d, "La linéarité donne u(x)−u(y)=u(x−y), puis la conservation de la norme donne celle de la distance."); }),
    task("scalar-product", "Transporter un produit scalaire", () => { const k = nz(); return number("Calculer ⟨u(x),u(y)⟩.", `u est une isométrie linéaire et ⟨x,y⟩ = ${k}.`, k, "Une isométrie linéaire conserve les produits scalaires."); }),
    task("adjoint-inverse", "Utiliser le lien entre adjoint et inverse", () => { const q = quarter(pick([1, 3])), x = vec(); return computedVector("Calculer u^{*}(x).", `Dans une base orthonormée, Mat(u) = ${M(q)}, x = ${C(x)}.`, "mv", [transpose(q), x], mv(transpose(q), x), "Pour une isométrie, u^{*}=u⁻¹ ; dans une base orthonormée sa matrice est Qᵀ."); }),
    task("real-eigenvalue", "Contraindre les valeurs propres réelles", () => { const a = pick([-1, 1]), norm = int(1, 5); return choice("Quelle contrainte impose l’isométrie sur λ ?", `u(x) = λx, x ≠ 0, λ ∈ ℝ, ‖x‖ = ${norm}. Une valeur admissible est ${a}.`, "λ ∈ {−1 ; 1}", ["λ = 1 uniquement", "λ ≥ 0", "λ ∈ {0 ; 1}"], "‖u(x)‖=|λ|‖x‖=‖x‖ impose |λ|=1."); }, true),
  ],
  "plane-rotation-engine": [
    task("rotate-vector", "Appliquer une rotation plane", () => { const k = pick([1, 2, 3]), x = vec(), a = quarter(k); return computedVector("Quelle est l’image de x par cette rotation ?", `Angle ${angle(k)}, orientation canonique, x = ${C(x)}.`, "mv", [a, x], mv(a, x), "On utilise la matrice (cos θ,−sin θ;sin θ,cos θ)."); }),
    task("compose-angles", "Composer deux rotations", () => { const a = pick([1, 2, 3]), b = pick([1, 2, 3]); return choice("Quel est l’angle de la composée, modulo 2π ?", `r a pour angle ${angle(a)}, s a pour angle ${angle(b)}.`, angle(a + b), [0, 1, 2, 3].filter(k => k !== (a + b) % 4).map(angle), "Les angles des rotations planes s’additionnent modulo 2π."); }),
    task("classify", "Distinguer rotation et réflexion", () => { const k = int(0, 3), reflection = Math.random() < 0.5, a = reflection ? mul(quarter(k), diag([1, -1])) : quarter(k); return choice("Quelle est la nature de cette isométrie plane ?", `A = ${M(a)}`, reflection ? "Une réflexion." : "Une rotation.", [reflection ? "Une rotation." : "Une réflexion.", "Une projection de rang 1.", "Une homothétie de rapport 2."], "En dimension 2, une matrice orthogonale de déterminant 1 est une rotation ; de déterminant −1, une réflexion."); }),
    task("reflection-axis", "Déterminer l’axe d’une réflexion", () => { const s = pick([-1, 1]); return choice("Quel est l’axe de la réflexion ?", `S = ${M([[0, s], [s, 0]])}`, `Vect((1 ; ${s}))`, [`Vect((1 ; ${-s}))`, "Vect((1 ; 0))", "Vect((0 ; 1))"], "L’axe est l’ensemble des vecteurs fixes, donc Ker(S−I)."); }),
    task("rotation-matrix", "Retrouver une matrice à partir d’un angle", () => { const k = pick([1, 2, 3]); return matrix("Quelle est la matrice de cette rotation dans la base canonique ?", `L’angle orienté est ${angle(k)}.`, quarter(k), "Les colonnes sont les images des vecteurs canoniques par la rotation."); }),
  ],
  "isometry-reducer": [
    task("fixed-dimension", "Lire la dimension de l’espace fixe", () => { const k = pick([1, 2, 3]), s = pick([-1, 1]), q = blockDiag(quarter(k), [[s]]); return number("Quelle est dim(Ker(Q−I)) ?", `Q = ${M(q)}`, s === 1 ? 1 : 0, "Une rotation plane d’angle non nul modulo 2π ne fixe aucun vecteur non nul ; le dernier bloc contribue une direction si son signe est +1."); }),
    task("orientation", "Lire l’orientation dans les blocs", () => { const k = int(0, 3), s = pick([-1, 1]), q = blockDiag(quarter(k), [[s]]); return yesno("L’isométrie est-elle directe ?", `Q = ${M(q)}`, s === 1, "Les blocs de rotation ont déterminant 1 ; le signe du bloc restant décide de l’orientation."); }),
    task("trace-angle", "Retrouver un cosinus par la trace en dimension trois", () => { const k = pick([0, 1, 2]), cosine = k === 0 ? 1 : k === 1 ? 0 : -1; return number("Quelle est la valeur de cos θ ?", `Q est une rotation de ℝ³ d’angle θ et tr(Q) = ${1 + 2 * cosine}.`, cosine, "La forme réduite est diag(1,R_θ), donc tr(Q)=1+2cos θ."); }),
    task("block-power", "Élever une forme orthogonale réduite à une puissance", () => { const k = pick([1, 3]), s = pick([-1, 1]), n = int(2, 5), q = blockDiag(quarter(k), [[s]]); return computedMatrix(`Calculer Q^{${n}}.`, `Q = ${M(q)}`, "power", [q, n], power(q, n), "Les blocs se traitent séparément : multiplier l’angle par n et élever le signe à la puissance n."); }),
    task("real-diagonalization", "Distinguer réduction orthogonale et diagonalisation réelle", () => { const k = pick([1, 2, 3]), q = blockDiag(quarter(k), [[1]]); return yesno("Q est-elle diagonalisable sur ℝ ?", `Q = ${M(q)}`, k === 2, "Les blocs de rotation sont diagonalisables sur ℝ seulement pour les angles 0 ou π ; un quart de tour a des valeurs propres non réelles."); }),
  ],
  "adjoint-chamber": [
    task("matrix-adjoint", "Calculer l’adjoint dans une base orthonormée", () => { const a = randomMatrix(3); return computedMatrix("Quelle est la matrice de u^{*} ?", `Dans une base orthonormée réelle, Mat(u) = ${M(a)}.`, "transpose", [a], transpose(a), "Dans une base orthonormée d’un espace euclidien réel, la matrice de l’adjoint est la transposée."); }),
    task("definition", "Utiliser l’identité définissant l’adjoint", () => choice("Quelle identité définit u^{*} ?", "u est un endomorphisme d’un espace euclidien réel ; l’identité vaut pour tous x et y.", "⟨u(x),y⟩ = ⟨x,u^{*}(y)⟩", ["⟨u(x),y⟩ = ⟨u^{*}(x),y⟩", "⟨u(x),y⟩ = ⟨x,u(y)⟩", "⟨u(x),y⟩ = −⟨x,u^{*}(y)⟩"], "L’adjoint transfère u du premier au second argument du produit scalaire."), true),
    task("composition", "Calculer l’adjoint d’une composée", () => { const a = randomMatrix(), b = randomMatrix(); return computedMatrix("Quelle est la matrice de (u ∘ v)^{*} ?", `Dans une base orthonormée, Mat(u) = ${M(a)}, Mat(v) = ${M(b)}.`, "transpose-product", [a, b], transpose(mul(a, b)), "L’adjoint renverse l’ordre : (uv)^{*}=v^{*}u^{*}, soit (AB)ᵀ=BᵀAᵀ."); }),
    task("gram-basis", "Calculer un adjoint dans une base non orthonormée", () => { const g = pick([2, 3, 4]), a = [[nz(), g * nz()], [nz(), nz()]], result = [[a[0][0], g * a[1][0]], [a[0][1] / g, a[1][1]]]; return matrix("Quelle est la matrice de l’adjoint dans cette base ?", `Mat_B(u) = ${M(a)} et la matrice de Gram de B est G = ${M(diag([1, g]))}.`, result, "Dans une base quelconque, Mat_B(u^{*})=G⁻¹AᵀG. On doit tenir compte de la matrice du produit scalaire."); }),
    task("kernel-adjoint", "Relier noyau de l’adjoint et image", () => { const n = int(3, 7), r = int(0, n); return number("Quelle est dim(Ker(u^{*})) ?", `E est euclidien de dimension ${n}, rg(u) = ${r}.`, n - r, "Ker(u^{*}) = Im(u)^{⊥}, dont la dimension vaut n−r."); }),
  ],
  "self-adjoint-symmetrizer": [
    task("recognize", "Reconnaître un endomorphisme autoadjoint", () => { const a = nz(), b = nz(), c = nz(), offset = pick([0, 1]); return yesno("u est-il autoadjoint ?", `Dans une base orthonormée, Mat(u) = ${M([[a, b], [b + offset, c]])}.`, offset === 0, "Dans une base orthonormée réelle, u est autoadjoint exactement quand sa matrice est symétrique."); }),
    task("complete", "Compléter une matrice symétrique", () => { const a = nz(), b = nz(), c = nz(); return number("Quelle valeur de t rend u autoadjoint ?", `Dans une base orthonormée, Mat(u) = ${M([[a, "t"], [b, c]])}.`, b, "Les coefficients symétriques par rapport à la diagonale doivent être égaux."); }),
    task("orthogonal-eigenvectors", "Exploiter l’orthogonalité des espaces propres", () => { const [a, b] = distinct(); return number("Quelle est la valeur de ⟨x,y⟩ ?", `u est autoadjoint, u(x) = ${lin([a], ["x"])}, u(y) = ${lin([b], ["y"])}.`, 0, "Les espaces propres d’un autoadjoint associés à des valeurs propres distinctes sont orthogonaux."); }),
    task("stable-orthogonal", "Restreindre à l’orthogonal d’un sous-espace stable", () => { const a = nz(), b = nz(), c = nz(), d = nz(); return matrix("Quelle est la matrice de u restreint à F^{⊥} dans (e₂,e₃) ?", `Dans une base orthonormée, A = ${M([[a, 0, 0], [0, b, c], [0, c, d]])}, F = Vect(e₁).`, [[b, c], [c, d]], "L’orthogonal d’un sous-espace stable par un autoadjoint est stable ; on lit le bloc correspondant."); }),
    task("symmetric-part", "Calculer la partie autoadjointe", () => { const a = [[2 * nz(), 2 * nz()], [2 * nz(), 2 * nz()]], result = times(0.5, plus(a, transpose(a))); return computedMatrix("Calculer la partie symétrique (A + Aᵀ)/2.", `A = ${M(a)}`, "symmetric-part", [a], result, "On moyenne chaque coefficient avec son symétrique ; le résultat est une matrice symétrique."); }),
  ],
  "orthogonal-diagonalizer": [
    task("spectral-theorem", "Appliquer le théorème spectral réel", () => choice("Quelle propriété possède toute matrice symétrique réelle ?", "A est une matrice symétrique réelle d’ordre n.", "Elle est diagonalisable dans une base orthonormée réelle.", ["Toutes ses valeurs propres sont positives.", "Elle est diagonale dans toute base orthonormée.", "Elle est nécessairement inversible."], "Le théorème spectral fournit une base orthonormée de vecteurs propres réels."), true),
    task("ordered-diagonal", "Respecter l’ordre d’une base propre orthonormée", () => { const a = nz(), b = nz(); return matrix("Quelle est la matrice de u dans B ?", `Dans la base canonique, Mat(u) = ${M([[a, b], [b, a]])}. B = (v₁,v₂), v₁ = ⟬1¦√2⟭${C([1, 1])}, v₂ = ⟬1¦√2⟭${C([1, -1])}.`, diag([a + b, a - b]), "v₁ est propre pour a+b et v₂ pour a−b : l’ordre de la diagonale suit celui de la base."); }),
    task("reconstruct", "Reconstruire une matrice à partir d’une réduction orthogonale", () => { const a = nz(), b = nz(), d = diag([2 * a, 2 * b]); return matrix("Calculer A = PDPᵀ.", `D = ${M(d)}, P = ⟬1¦√2⟭${M([[1, 1], [1, -1]])}`, [[a + b, a - b], [a - b, a + b]], "Les deux facteurs 1/√2 donnent 1/2 ; le produit fournit les demi-sommes et demi-différences des valeurs propres."); }),
    task("quadratic-extremum", "Optimiser une forme quadratique sur la sphère", () => { const a = nz(), b = nz(); return number("Quelle est la plus grande valeur de xᵀAx pour ‖x‖ = 1 ?", `A = ${M([[a, b], [b, a]])}`, a + Math.abs(b), "Pour une symétrique, le maximum sur la sphère unité est la plus grande valeur propre ; ici les valeurs propres sont a+b et a−b."); }),
    task("spectral-power", "Calculer une puissance par diagonalisation orthogonale", () => { const a = nz(), b = nz(), A = [[a, b], [b, a]], k = int(2, 3); return computedMatrix(`Calculer A^{${k}}.`, `A = ${M(A)}`, "power", [A, k], power(A, k), "Une base propre orthonormée est donnée par (1;1)/√2 et (1;−1)/√2 ; on élève les valeurs propres à la puissance k."); }),
  ],
  "positivity-analyzer": [
    task("classify-sign", "Distinguer positive, définie positive et non positive", () => { const category = int(0, 2), a = int(1, 4), b = category === 0 ? int(1, 4) : category === 1 ? 0 : -int(1, 4); return choice("Quelle affirmation décrit A ?", `A = ${M(diag([a, b]))}`, category === 0 ? "A est définie positive." : category === 1 ? "A est positive mais non définie positive." : "A n’est pas positive.", [category === 0 ? "A est positive mais non définie positive." : "A est définie positive.", category === 2 ? "A est positive mais non définie positive." : "A n’est pas positive.", "A est définie négative."], "Une symétrique est positive si toutes ses valeurs propres sont ≥0, et définie positive si elles sont toutes >0."); }),
    task("sylvester-parameter", "Trouver un seuil de positivité stricte", () => { const a = nz(), threshold = a * a; return choice("Pour quelles valeurs de t A est-elle définie positive ?", `A = ${M([[1, a], [a, "t"]])}`, `t > ${threshold}`, [`t ≥ ${threshold}`, `t < ${threshold}`, "Tout réel t"], "Le premier mineur vaut 1 ; le déterminant doit être strictement positif, soit t−a²>0."); }),
    task("quadratic-value", "Évaluer une forme quadratique", () => { const a = randomMatrix(), A = plus(a, transpose(a)), x = vec(), value = dot(x, mv(A, x)); return number("Calculer xᵀAx.", `A = ${M(A)}, x = ${C(x)}`, value, "On calcule Ax puis le produit scalaire de x avec Ax.", { kind: "quadratic", inputs: [A, x], expected: value }); }),
    task("gram-definiteness", "Étudier la positivité de BᵀB", () => { const a = nz(), full = Math.random() < 0.5, B = [[1, a], [0, full ? 1 : 0]]; return yesno("BᵀB est-elle définie positive ?", `B = ${M(B)}`, full, "xᵀBᵀBx=‖Bx‖² ; la positivité est stricte pour tout x non nul exactement lorsque Ker(B)={0}."); }),
    task("positive-square-root", "Construire la racine carrée positive d’une diagonale", () => { const a = int(1, 5), b = int(1, 5); return matrix("Quelle est l’unique matrice symétrique positive S telle que S² = A ?", `A = ${M(diag([a * a, b * b]))}`, diag([a, b]), "On prend les racines carrées positives des valeurs propres dans une base orthonormée propre."); }),
  ],
};
