import { task, int, nz, pick, V, C, M, R, lin, vec, randomMatrix, shear, diag, eye, mul, mv, transpose, det, trace, power, plus, times, number, vector, matrix, choice, yesno, computedMatrix, computedVector, type Matrix, type WorkshopTasks } from "./core.ts";

const determinantTask = (size: number) => task(`det-${size}`, `Calculer un déterminant d’ordre ${size}`, () => {
  const a = randomMatrix(size);
  if (size > 2) { a[2][0] = 0; a[2][1] = 0; }
  return number("Calculer det(A).", `A = ${M(a)}`, det(a), size === 2 ? "Pour une matrice d’ordre 2 : det(A) = a₁₁a₂₂ − a₁₂a₂₁." : "Développer suivant la dernière ligne, qui contient deux zéros.", { kind: "det", inputs: [a], expected: det(a) });
});
const productTask = (id: string, label: string, reverse = false) => task(id, label, () => {
  const a = randomMatrix(), b = randomMatrix();
  return computedMatrix(`Calculer ${reverse ? "BA" : "AB"}.`, `A = ${M(a)}, B = ${M(b)}`, "mul", reverse ? [b, a] : [a, b], reverse ? mul(b, a) : mul(a, b), "Chaque entrée est un produit ligne-colonne.");
});
const inverse = (a: Matrix): Matrix => { const d = det(a); return [[a[1][1] / d, -a[0][1] / d], [-a[1][0] / d, a[0][0] / d]]; };
const unimodular = (): Matrix => mul(shear(), transpose(shear()));

export const matrices: WorkshopTasks = {
  "matrix-encoder": [
    task("columns", "Construire la matrice à partir des images d’une base", () => { const a = randomMatrix(3, 2); return matrix("Quelle est la matrice de f dans les bases canoniques ?", `f : ℝ² → ℝ³, f(e₁) = ${C(a.map(r => r[0]))}, f(e₂) = ${C(a.map(r => r[1]))}`, a, "Les images des vecteurs de la base de départ se placent en colonnes, dans l’ordre."); }),
    task("basis-image", "Lire l’image d’un vecteur de base", () => { const a = randomMatrix(3), j = int(0, 2); return vector(`Quelles sont les coordonnées de f(e_{${j + 1}}) ?`, `Mat(f) = ${M(a)} dans les bases canoniques.`, a.map(r => r[j]), "L’image du j-ième vecteur canonique est la j-ième colonne.", true); }),
    task("linear-image", "Calculer une image à partir de la matrice", () => { const a = randomMatrix(), x = vec(); return computedVector("Calculer les coordonnées de f(x).", `Mat(f) = ${M(a)}, [x] = ${C(x)}`, "mv", [a, x], mv(a, x), "La relation entre coordonnées est [f(x)] = Mat(f)[x]."); }),
    task("matrix-shape", "Déterminer le format d’une représentation", () => { const m = int(2, 4), n = m + int(1, 2); return choice("Quel est le format de Mat(f) ?", `f : ${R(n)} → ${R(m)} est linéaire.`, `${m} lignes et ${n} colonnes`, [`${n} lignes et ${m} colonnes`, `${m} lignes et ${m} colonnes`, `${n} lignes et ${n} colonnes`], "Une colonne par vecteur de la base de départ, une ligne par coordonnée d’arrivée."); }),
    task("polynomial-matrix", "Représenter une application sur les polynômes", () => { const a = nz(); return matrix("Quelle est la matrice de f dans B = (1, X, X²) ?", `f(P) = ${lin([a], ["P"])} + P′ sur ℝ₂[X].`, [[a, 1, 0], [0, a, 2], [0, 0, a]], "On calcule successivement f(1), f(X) et f(X²), puis on place leurs coordonnées en colonnes."); }),
  ],
  "matrix-composer": [
    productTask("product", "Calculer un produit matriciel"),
    task("commutator", "Calculer un commutateur", () => { const a = randomMatrix(), b = randomMatrix(); const ab = mul(a, b), ba = mul(b, a); return computedMatrix("Calculer AB − BA.", `A = ${M(a)}, B = ${M(b)}`, "commutator", [a, b], plus(ab, times(-1, ba)), "Les deux produits se calculent dans leur ordre respectif."); }),
    task("format", "Vérifier la compatibilité d’un produit", () => { const m = int(2, 4), n = m + 1, p = n + 1; return choice("Quel est le format de AB ?", `A a ${m} lignes et ${n} colonnes ; B a ${n} lignes et ${p} colonnes.`, `${m} lignes et ${p} colonnes`, [`${n} lignes et ${n} colonnes`, `${p} lignes et ${m} colonnes`, "Le produit n’est pas défini."], "Les dimensions intérieures coïncident ; les dimensions extérieures donnent celles du produit."); }),
    task("power", "Calculer une puissance matricielle", () => { const a = shear(), k = int(2, 5); return computedMatrix(`Calculer A^{${k}}.`, `A = ${M(a)}`, "power", [a, k], power(a, k), "La matrice est I + N avec N² = 0 ; la puissance est I + kN."); }),
    task("transpose-product", "Transposer un produit", () => { const a = randomMatrix(), b = randomMatrix(); return computedMatrix("Calculer (AB)ᵀ.", `A = ${M(a)}, B = ${M(b)}`, "transpose-product", [a, b], transpose(mul(a, b)), "La transposition renverse l’ordre : (AB)ᵀ = BᵀAᵀ."); }),
  ],
  "canonical-matrix-link": [
    task("apply", "Appliquer l’application canoniquement associée", () => { const a = randomMatrix(2, 3), x = vec(3); return computedVector("Calculer f_A(x).", `f_A : ℝ³ → ℝ², f_A(x) = Ax, A = ${M(a)}, x = ${C(x)}`, "mv", [a, x], mv(a, x), "On multiplie A par le vecteur colonne x."); }),
    task("recover-domain", "Retrouver l’espace de départ", () => { const m = int(2, 4), n = m + int(1, 2); return number("Quelle est la dimension du domaine de f_A ?", `A possède ${m} lignes et ${n} colonnes ; f_A est son application canonique.`, n, "Le vecteur que l’on multiplie à droite doit avoir autant de coordonnées que A a de colonnes."); }),
    task("preimage", "Calculer un antécédent", () => { const a = unimodular(), x = vec(); return computedVector("Résoudre f_A(x) = b.", `A = ${M(a)}, b = ${C(mv(a, x))}`, "solve", [a, mv(a, x)], x, "La matrice est inversible ; résoudre Ax = b donne un unique antécédent."); }),
    task("basis-columns", "Associer les colonnes aux images canoniques", () => { const a = randomMatrix(2, 3), j = int(0, 2); return vector(`Calculer f_A(e_{${j + 1}}).`, `A = ${M(a)}`, a.map(r => r[j]), "Multiplier par un vecteur canonique sélectionne la colonne de même indice.", true); }),
    task("injectivity", "Décider l’injectivité de l’application canonique", () => { const n = int(2, 5), r = pick([n, n - 1]); return yesno("f_A est-elle injective ?", `A possède ${n + 1} lignes et ${n} colonnes, rg(A) = ${r}.`, r === n, "L’application canonique est injective si ses colonnes sont indépendantes, donc si le rang vaut le nombre de colonnes."); }),
  ],
  "matrix-kernel-imager": [
    task("null-vector", "Trouver un vecteur du noyau matriciel", () => { const a = nz(), b = nz(), A = [[1, a], [b, a * b]]; return choice("Quel vecteur non nul appartient à Ker(A) ?", `A = ${M(A)}`, C([-a, 1]), [C([a, 1]), C([1, 0]), C([0, 1])], "Les deux lignes donnent la même équation x + ay = 0."); }),
    task("image", "Décrire l’espace engendré par les colonnes", () => { const a = nz(), b = nz(); return choice("Quelle est Im(A) ?", `A = ${M([[1, a], [b, a * b]])}`, `Vect(${C([1, b])})`, ["ℝ²", "{0}", `Vect(${C([0, 1])})`], "La seconde colonne est a fois la première, et la première est non nulle."); }),
    task("rank", "Calculer le rang en lisant les colonnes", () => { const a = nz(), b = pick([0, nz()]); return number("Quel est le rang de A ?", `A = ${M([[1, a, 0], [0, 0, b]])}`, b ? 2 : 1, b ? "Les première et troisième colonnes sont indépendantes." : "Toutes les colonnes sont multiples de la première."); }),
    task("nullity", "Passer du rang à la dimension du noyau", () => { const a = nz(), b = nz(); return number("Quelle est la dimension de Ker(A) ?", `A = ${M([[1, a, 0, b], [0, 0, 1, 1]])}`, 2, "Les deux lignes sont indépendantes. Avec quatre inconnues, la nullité vaut 4 − 2."); }),
    task("compatible-image", "Tester si un second membre est dans l’image", () => { const a = nz(), t = nz(), offset = pick([0, 1]); return yesno("Le système AX = b admet-il une solution ?", `A = ${M([[1, 2], [a, 2 * a]])}, b = ${C([t, a * t + offset])}`, offset === 0, "L’image est dirigée par (1 ; a), donc le second membre doit vérifier b₂ = ab₁."); }),
  ],
  "system-solver": [
    task("unique-solution", "Résoudre un système à solution unique", () => { const a = unimodular(), x = vec(), b = mv(a, x); return computedVector("Résoudre AX = b.", `A = ${M(a)}, b = ${C(b)}`, "solve", [a, b], x, "L’élimination ou l’inverse de A fournit la solution."); }),
    task("compatibility-parameter", "Trouver un paramètre de compatibilité", () => { const a = nz(), b = nz(); return number("Pour quelle valeur de t le système est-il compatible ?", `x + y = ${b} et ${lin([a, a])} = t`, a * b, "La seconde équation a un membre de gauche égal à a fois celui de la première ; il faut la même relation à droite."); }),
    task("solution-family", "Décrire toutes les solutions", () => { const a = nz(), b = nz(); return choice("Quel ensemble décrit toutes les solutions ?", `${lin([1, a])} = ${b}`, `{(${lin([-a], ["t"])} ${b < 0 ? "−" : "+"} ${Math.abs(b)} ; t) | t ∈ ℝ}`, ["{(0 ; 0)}", `{(${b} ; 0)}`, `{(t ; ${b}) | t ∈ ℝ}`], "On choisit y = t puis x = b − at. Il faut conserver tous les paramètres réels."); }),
    task("solution-dimension", "Calculer la dimension de l’ensemble des solutions", () => { const n = int(3, 7), r = int(1, n - 1); return number("Quelle est la dimension de l’ensemble des solutions ?", `AX = b est compatible ; A a ${n} colonnes et son rang vaut ${r}.`, n - r, "Une solution particulière translate le noyau, dont la dimension est n − r."); }),
    task("eliminate-row", "Effectuer une étape du pivot", () => { const a = nz(), b = nz(), c = nz(), d = nz(); return vector("Quelle devient la seconde ligne augmentée après L₂ ← L₂ − aL₁ ?", `a = ${a}, matrice augmentée ${M([[1, b, c], [a, d, 1]])}`, [0, d - a * b, 1 - a * c], "L’opération s’applique à tous les coefficients, y compris le second membre."); }),
  ],
  "gauss-inverter": [
    task("inverse", "Calculer une matrice inverse", () => { const a = unimodular(), result = inverse(a); return computedMatrix("Calculer A⁻¹.", `A = ${M(a)}`, "inverse", [a], result, "La matrice inverse vérifie AA⁻¹ = I."); }),
    task("elementary-inverse", "Inverser une opération élémentaire", () => { const a = nz(); return matrix("Quelle matrice annule l’opération L₁ ← L₁ + aL₂ ?", `a = ${a} ; l’opération initiale est la multiplication à gauche par ${M(shear(a))}.`, shear(-a), "Pour annuler l’ajout de a fois la seconde ligne, on soustrait a fois cette ligne."); }),
    task("singular-parameter", "Détecter un pivot nul selon un paramètre", () => { const a = nz(), b = nz(); return number("Pour quelle valeur de t A n’est-elle pas inversible ?", `A = ${M([[1, a], [b, "t"]])}`, a * b, "Après L₂ ← L₂ − bL₁, le second pivot est t − ab."); }),
    task("inverse-product", "Inverser un produit dans le bon ordre", () => { const a = shear(), b = transpose(shear()), product = mul(a, b); return computedMatrix("Calculer (AB)⁻¹.", `A = ${M(a)}, B = ${M(b)}`, "inverse", [product], inverse(product), "La formule est (AB)⁻¹ = B⁻¹A⁻¹."); }),
    task("inverse-system", "Utiliser une inverse pour résoudre un système", () => { const inv = unimodular(), b = vec(); return computedVector("Résoudre AX = b.", `A⁻¹ = ${M(inv)}, b = ${C(b)}`, "mv", [inv, b], mv(inv, b), "On multiplie le second membre par A⁻¹."); }),
  ],
  "matrix-rank-reducer": [
    task("pivots", "Compter les pivots d’une matrice échelonnée", () => { const a = nz(), b = pick([0, nz()]); return number("Quel est le rang de A ?", `A = ${M([[a, 1, 2], [0, b, 1], [0, 0, 0]])}`, 2, "Il y a deux lignes non nulles indépendantes : la seconde possède toujours un pivot, même si son coefficient central est nul."); }),
    task("parameter-rank", "Étudier une chute de rang", () => { const a = nz(), t = pick([0, nz()]); return number("Quel est le rang de A ?", `A = ${M([[1, a, 0], [0, t, 0], [0, 0, 1]])}`, t === 0 ? 2 : 3, "La première et la troisième colonnes donnent deux pivots ; le pivot central existe exactement si t ≠ 0."); }),
    task("transpose-rank", "Relier le rang à celui de la transposée", () => { const r = int(0, 4); return number("Quel est le rang de Aᵀ ?", `A possède 4 lignes et 6 colonnes, rg(A) = ${r}.`, r, "La transposition conserve le rang."); }),
    task("canonical-rank", "Lire une forme canonique d’équivalence", () => { const n = int(3, 6), r = int(1, n - 1); const a = diag(Array.from({ length: n }, (_, i) => +(i < r))); return number("Quel est le rang de J ?", `J = ${M(a)}`, r, "Le rang est le nombre de coefficients 1 du bloc identité."); }),
    task("row-operation", "Suivre le rang sous une opération élémentaire", () => { const r = int(1, 4), k = nz(); return number("Quel est le rang de B ?", `rg(A) = ${r} ; B est obtenue par L₂ ← L₂ + (${k})L₁.`, r, "L’opération est inversible et ne change pas l’espace engendré par les lignes."); }),
  ],
  "matrix-equivalence-classifier": [
    task("same-rank", "Reconnaître deux matrices équivalentes", () => { const r = int(1, 3), s = pick([r, (r % 3) + 1]); return yesno("A et B sont-elles équivalentes ?", `A et B ont 3 lignes et 4 colonnes ; rg(A) = ${r}, rg(B) = ${s}.`, r === s, "Deux matrices de même format sont équivalentes exactement lorsqu’elles ont le même rang."); }),
    task("change-bases", "Calculer une transformation PAQ", () => { const a = randomMatrix(), p = shear(), q = transpose(shear()); return computedMatrix("Calculer PAQ.", `P = ${M(p)}, A = ${M(a)}, Q = ${M(q)}`, "triple-product", [p, a, q], mul(mul(p, a), q), "On effectue les produits dans l’ordre indiqué."); }),
    task("canonical-form", "Choisir la forme canonique d’équivalence", () => { const r = int(1, 3); const a = diag([1, +(r > 1), +(r > 2)]); return matrix("Quelle est la forme J_r canonique d’équivalence ?", `A est d’ordre 3 et rg(A) = ${r}.`, a, "J_r porte un bloc identité d’ordre r en haut à gauche et des zéros ailleurs."); }),
    task("rank-invariance", "Utiliser l’inversibilité des changements de bases", () => { const r = int(1, 4); return number("Quel est le rang de PAQ ?", `A possède 4 lignes et 5 colonnes, rg(A) = ${r}, P ∈ GL₄(ℝ), Q ∈ GL₅(ℝ).`, r, "La multiplication à gauche et à droite par des matrices inversibles conserve le rang."); }),
    task("equivalence-not-similarity", "Distinguer équivalence et similitude", () => { const a = pick([2, 3, 4]); return choice("Quelle affirmation est correcte ?", `A = I₂ et B = ${M(diag([1, a]))}`, "A et B sont équivalentes, mais non semblables.", ["A et B sont semblables.", "A et B ne sont pas équivalentes.", "A et B ont des rangs différents."], "Les deux rangs valent 2. Cependant toute matrice semblable à I₂ est I₂, et B ≠ I₂."); }),
  ],
  "passage-matrix-forge": [
    task("columns", "Construire une matrice de passage", () => { const p = unimodular(); return matrix("Quelle matrice P vérifie [x]_can = P[x]_B ?", `B = (${V(p.map(r => r[0]))}, ${V(p.map(r => r[1]))})`, p, "Les colonnes sont les vecteurs de B exprimés dans la base canonique."); }),
    task("reverse-passage", "Inverser le sens d’un passage", () => { const p = unimodular(); return computedMatrix("Quelle matrice Q vérifie [x]_B = Q[x]_can ?", `[x]_can = P[x]_B, P = ${M(p)}`, "inverse", [p], inverse(p), "Inverser le sens du passage revient à inverser P."); }),
    task("compose-passages", "Composer deux changements de coordonnées", () => { const p = shear(), q = transpose(shear()); return computedMatrix("Quelle matrice R vérifie [x]_B = R[x]_D ?", `[x]_B = P[x]_C, [x]_C = Q[x]_D, P = ${M(p)}, Q = ${M(q)}`, "mul", [p, q], mul(p, q), "La substitution donne [x]_B = PQ[x]_D."); }),
    task("transport", "Appliquer une matrice de passage", () => { const p = unimodular(), x = vec(); return computedVector("Calculer [x]_can.", `[x]_can = P[x]_B, P = ${M(p)}, [x]_B = ${C(x)}`, "mv", [p, x], mv(p, x), "On multiplie les coordonnées dans B par P."); }),
    task("valid-passage", "Vérifier qu’un passage est possible", () => { const a = nz(), b = nz(); return number("Pour quelle valeur de t P ne peut-elle pas être une matrice de passage ?", `P = ${M([[1, a], [b, "t"]])}`, a * b, "Une matrice de passage doit être inversible ; son déterminant t − ab doit être non nul."); }),
  ],
  "coordinate-transporter": [
    task("to-canonical", "Passer d’une base aux coordonnées canoniques", () => { const p = unimodular(), x = vec(); return computedVector("Calculer [x]_can.", `B = (${V(p.map(r => r[0]))}, ${V(p.map(r => r[1]))}), [x]_B = ${C(x)}`, "mv", [p, x], mv(p, x), "On combine les vecteurs de la base avec les coefficients de x."); }),
    task("from-canonical", "Exprimer un vecteur dans une nouvelle base", () => { const p = unimodular(), x = vec(), can = mv(p, x); return computedVector("Calculer [x]_B.", `B = (${V(p.map(r => r[0]))}, ${V(p.map(r => r[1]))}), [x]_can = ${C(can)}`, "solve", [p, can], x, "On résout P[x]_B = [x]_can."); }),
    task("between-bases", "Transporter entre deux bases non canoniques", () => { const p = shear(), q = transpose(shear()), x = vec(); const result = mv(mul(inverse(q), p), x); return computedVector("Calculer [x]_C.", `[x]_can = P[x]_B = Q[x]_C, P = ${M(p)}, Q = ${M(q)}, [x]_B = ${C(x)}`, "mv", [mul(inverse(q), p), x], result, "Le changement de coordonnées est [x]_C = Q⁻¹P[x]_B."); }),
    task("polynomial-coordinates", "Changer de base dans un espace de polynômes", () => { const a = nz(), x = nz(), y = nz(); return vector("Quelles sont les coordonnées de P dans B ?", `B = (1, X ${a < 0 ? "−" : "+"} ${Math.abs(a)}), P(X) = ${lin([y], ["X"])} ${x < 0 ? "−" : "+"} ${Math.abs(x)}`, [x - a * y, y], "Écrire P = α + β(X + a) donne β = y et α = x − ay.", true); }),
    task("recover-coefficient", "Retrouver une coordonnée manquante", () => { const a = nz(), x = nz(), y = nz(); return number("Quelle est la valeur de t ?", `B = ((1 ; 0), (${a} ; 1)), [u]_B = (t ; ${y}), [u]_can = ${V([x + a * y, y])}`, x, "La première coordonnée canonique vaut t + ay."); }),
  ],
  "similarity-chamber": [
    task("conjugate", "Calculer une matrice semblable", () => { const a = randomMatrix(), p = shear(); return computedMatrix("Calculer P⁻¹AP.", `A = ${M(a)}, P = ${M(p)}`, "triple-product", [inverse(p), a, p], mul(mul(inverse(p), a), p), "Le changement de base d’un endomorphisme est une conjugaison."); }),
    task("trace-obstruction", "Exclure la similitude par la trace", () => { const a = nz(), b = nz(); return yesno("Ces matrices peuvent-elles être semblables ?", `A = ${M(diag([a, b]))}, B = ${M(diag([a + 1, b]))}`, false, "Leurs traces diffèrent d’une unité ; des matrices semblables ont la même trace."); }),
    task("same-invariants", "Distinguer invariants nécessaires et suffisants", () => { const a = nz(), b = nz(); return yesno("A et B sont-elles semblables ?", `A = ${M(diag([a, a]))}, B = ${M([[a, b], [0, a]])}`, false, "Toute conjugaison d’une matrice scalaire la laisse inchangée. B n’est pas scalaire, même si trace et déterminant coïncident."); }),
    task("intertwining", "Utiliser la relation AP = PB", () => { const b = randomMatrix(), p = shear(); const a = mul(mul(p, b), inverse(p)); return computedMatrix("Quelle matrice A vérifie AP = PB ?", `P = ${M(p)}, B = ${M(b)}`, "triple-product", [p, b, inverse(p)], a, "On multiplie l’égalité à droite par P⁻¹ : A = PBP⁻¹."); }),
    task("power-conjugation", "Transporter une puissance par similitude", () => { const a = int(1, 3), b = int(-3, -1), p = shear(), k = int(2, 3); const d = diag([a, b]), A = mul(mul(p, d), inverse(p)); return computedMatrix(`Calculer A^{${k}}.`, `A = PDP⁻¹, D = ${M(d)}, P = ${M(p)}`, "power", [A, k], mul(mul(p, power(d, k)), inverse(p)), "Les facteurs P⁻¹P se simplifient : A^k = PD^kP⁻¹."); }),
  ],
  "trace-observer": [
    task("read-trace", "Calculer une trace", () => { const a = randomMatrix(3); return number("Calculer tr(A).", `A = ${M(a)}`, trace(a), "La trace est la somme des coefficients diagonaux.", { kind: "trace", inputs: [a], expected: trace(a) }); }),
    task("linearity", "Utiliser la linéarité de la trace", () => { const a = nz(), b = nz(), s = nz(), t = nz(); return number(`Calculer tr(${lin([a, b], ["A", "B"])}).`, `tr(A) = ${s}, tr(B) = ${t}.`, a * s + b * t, "La trace est une forme linéaire : tr(aA + bB) = a tr(A) + b tr(B)."); }),
    task("product-trace", "Calculer la trace d’un produit", () => { const a = randomMatrix(), b = randomMatrix(); return number("Calculer tr(AB).", `A = ${M(a)}, B = ${M(b)}`, trace(mul(a, b)), "Seuls les deux coefficients diagonaux du produit sont nécessaires.", { kind: "trace-product", inputs: [a, b], expected: trace(mul(a, b)) }); }),
    task("commutator-trace", "Utiliser la cyclicité", () => { const k = nz(); return number(`Calculer tr(${lin([k], ["(AB − BA)"])}).`, "A et B sont deux matrices carrées de même ordre.", 0, "La cyclicité tr(AB) = tr(BA) rend la trace de tout commutateur nulle."); }),
    task("projector-trace", "Relier trace et rang d’un projecteur", () => { const n = int(3, 7), r = int(0, n); return number("Quelle est la trace du projecteur p ?", `dim(E) = ${n}, dim(Im(p)) = ${r}.`, r, "Dans une base adaptée à Im(p) ⊕ Ker(p), la matrice porte r coefficients 1 et les autres coefficients diagonaux sont nuls."); }),
  ],
  "permutation-signature": [
    task("inversions", "Calculer une signature par les inversions", () => { const p = [1, 2, 3, 4].sort(() => Math.random() - 0.5); let inv = 0; p.forEach((x, i) => p.slice(i + 1).forEach(y => { if (x > y) inv++; })); return number("Quelle est la signature de σ ?", `σ(1), σ(2), σ(3), σ(4) = ${V(p)}`, (-1) ** inv, `Il y a ${inv} inversions. La signature vaut (−1)^{${inv}}.`); }),
    task("cycle", "Signer un cycle", () => { const n = int(2, 8); return number("Quelle est la signature de ce cycle ?", `σ = (1 2 … ${n})`, (-1) ** (n - 1), `Un cycle de longueur ${n} est un produit de ${n - 1} transpositions.`); }),
    task("disjoint-cycles", "Signer un produit de cycles disjoints", () => { const a = int(2, 5), b = int(2, 5); return number("Quelle est la signature de σ ?", `σ est le produit de deux cycles disjoints de longueurs ${a} et ${b}.`, (-1) ** (a + b - 2), "La signature est multiplicative ; chaque cycle de longueur k contribue (−1)^(k−1)."); }),
    task("inverse", "Signer l’inverse d’une permutation", () => { const a = pick([-1, 1]), k = int(2, 7); return number(`Quelle est la signature de (σ⁻¹)^{${k}} ?`, `ε(σ) = ${a}`, a ** k, "La signature de l’inverse est égale à la signature ; celle d’une puissance est la puissance de la signature."); }),
    task("composition", "Composer deux permutations", () => { const p = [2, 3, 1, 4], q = [4, 2, 3, 1], i = int(1, 4); return number(`Calculer (σ ∘ τ)(${i}).`, `σ : ${V(p)}, τ : ${V(q)} ; chaque liste donne les images de 1, 2, 3, 4.`, p[q[i - 1] - 1], "On calcule d’abord τ(i), puis son image par σ."); }),
  ],
  "determinant-forge": [
    determinantTask(2),
    determinantTask(3),
    task("row-swap", "Suivre un échange de lignes", () => { const d = nz(); return number("Quel est det(B) ?", `det(A) = ${d} ; B est obtenue en échangeant deux lignes distinctes de A.`, -d, "Un échange de deux lignes change le signe du déterminant."); }),
    task("scalar-multiple", "Multiplier toute une matrice par un scalaire", () => { const n = int(2, 4), k = pick([-2, 2, 3]), d = nz(); return number(`Calculer det(${k}A).`, `A est d’ordre ${n} et det(A) = ${d}.`, k ** n * d, "Chaque ligne est multipliée par k, donc le déterminant est multiplié par k^n."); }),
    task("product", "Utiliser la multiplicativité du déterminant", () => { const a = nz(), b = nz(); return number("Calculer det(AB).", `A et B sont carrées de même ordre, det(A) = ${a}, det(B) = ${b}.`, a * b, "Le déterminant d’un produit est le produit des déterminants."); }),
  ],
  "cofactor-expander": [
    task("cofactor", "Calculer un cofacteur avec son signe", () => { const a = randomMatrix(3), i = int(0, 2), j = int(0, 2); const minor = a.filter((_, r) => r !== i).map(row => row.filter((_, c) => c !== j)), value = (-1) ** (i + j) * det(minor); return number(`Calculer le cofacteur C_{${i + 1}${j + 1}}.`, `A = ${M(a)}`, value, `On retire la ligne ${i + 1} et la colonne ${j + 1}, puis on multiplie le mineur par (−1)^{${i + j + 2}}.`, { kind: "cofactor", inputs: [a, i, j], expected: value }); }),
    task("minor", "Calculer un mineur", () => { const a = randomMatrix(3), minor = a.slice(1).map(row => row.slice(1)); return number("Calculer le mineur obtenu en retirant la première ligne et la première colonne.", `A = ${M(a)}`, det(minor), "Le mineur est le déterminant de la sous-matrice restante.", { kind: "det", inputs: [minor], expected: det(minor) }); }),
    determinantTask(3),
    task("sparse-four", "Développer un déterminant d’ordre quatre", () => { const a = randomMatrix(), b = nz(), c = nz(); const A = [[...a[0], 0, 0], [...a[1], 0, 0], [0, 0, b, 1], [0, 0, 0, c]]; return number("Calculer det(A).", `A = ${M(A)}`, det(A), "Développer suivant la dernière ligne, puis suivant la troisième : il reste un déterminant d’ordre 2.", { kind: "det", inputs: [A], expected: det(A) }); }),
    task("entry-variation", "Relier un cofacteur à la variation d’un coefficient", () => { const a = randomMatrix(3), k = nz(), cofactor = det(a.slice(1).map(r => r.slice(1))); return number("De combien le déterminant augmente-t-il ?", `A = ${M(a)} ; seul a₁₁ est augmenté de ${k}.`, k * cofactor, "Le développement suivant la première ligne est affine en a₁₁ : la variation vaut kC₁₁."); }),
  ],
  "vandermonde-adjugate": [
    task("vandermonde", "Calculer un déterminant de Vandermonde", () => { const a = int(-3, 0), b = a + int(1, 2), c = b + int(1, 2), A = [[1, a, a * a], [1, b, b * b], [1, c, c * c]]; return number("Calculer det(V).", `V = ${M(A)}`, (b - a) * (c - a) * (c - b), "Avec les points en lignes et les puissances croissantes en colonnes, le déterminant vaut (b−a)(c−a)(c−b).", { kind: "det", inputs: [A], expected: det(A) }); }),
    task("vandermonde-singular", "Reconnaître un Vandermonde singulier", () => { const a = nz(), b = a + 2; return choice("Pour quelles valeurs de t V est-elle singulière ?", `Les lignes de V sont (1, a, a²), (1, b, b²), (1, t, t²), avec a = ${a}, b = ${b}.`, `t ∈ {${a} ; ${b}}`, [`t = ${a + 1}`, `t = ${b + 1}`, "Aucune valeur réelle."], "Le déterminant s’annule exactement lorsque deux points d’évaluation coïncident."); }),
    task("adjugate", "Calculer la transposée de la comatrice", () => { const a = randomMatrix(); return matrix("Calculer adj(A), la transposée de la comatrice.", `A = ${M(a)}`, [[a[1][1], -a[0][1]], [-a[1][0], a[0][0]]], "Pour une matrice (a,b;c,d), l’adjugée est (d,−b;−c,a)."); }),
    task("adjugate-identity", "Utiliser l’identité de la comatrice", () => { const a = randomMatrix(); return matrix("Calculer A adj(A).", `A = ${M(a)}, adj(A) désigne la transposée de la comatrice.`, times(det(a), eye(2)), "L’identité A adj(A) = det(A)I reste vraie même si A n’est pas inversible."); }),
    task("inverse-comatrix", "Obtenir l’inverse à partir de la comatrice", () => { const a = unimodular(); return computedMatrix("Calculer A⁻¹ à l’aide de la comatrice.", `A = ${M(a)}`, "inverse", [a], inverse(a), "L’inverse est adj(A)/det(A) ; ici le déterminant vaut 1."); }),
  ],
};
